### ISSUE TITLE
Bug in getting values a, b, c, d i.e. they only being extracted with int values.

### ISSUE THREAD

**Issue by rolex4301** [ahanapradhan/UnionExtraction#127]
![Screenshot from 2024-05-24 10-10-18](https://github.com/ahanapradhan/UnionExtraction/assets/159542768/b9cdbe63-f71e-407c-a0f2-0499cd8d02d9)

**Comment by ahanapradhan** [comment]
@rolex4301 is this issue already resolved in an earlier PR?

**Comment by rolex4301** [comment]
I have solved it today ma'am and haven't raised PR and still have to check.

**Comment by ahanapradhan** [comment]
closed https://github.com/ahanapradhan/UnionExtraction/pull/132
