### ISSUE TITLE
Order by bug

### ISSUE THREAD

**Issue by ahanapradhan** [ahanapradhan/UnionExtraction#134]
Input:
"Select c_name, sum(l_extendedprice * (1 - l_discount)) as revenue, c_acctbal, n_name, c_address, " \
      "c_phone, c_comment From customer, orders, lineitem, nation " \
      "Where c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate >= date '1994-01-01' " \
      "and o_orderdate < date '1994-01-01' + interval '3' month and l_returnflag = 'R' and c_nationkey = n_nationkey " \
      "Group By c_name, c_acctbal, c_phone, n_name, c_address, c_comment Order by revenue desc Limit 20;"

Extracted Query:
Select c_name, Sum(l_extendedprice*(1 - l_discount)) as revenue, c_acctbal, n_name, c_address, c_phone, c_comment 
 From customer, lineitem, nation, orders 
 Where customer.c_custkey = orders.o_custkey
 and customer.c_nationkey = nation.n_nationkey
 and lineitem.l_orderkey = orders.o_orderkey
 and orders.o_orderdate between '1994-01-01' and '1994-03-31'
 and lineitem.l_returnflag = 'R' 
 Group By c_acctbal, c_address, c_comment, c_name, c_phone, n_name 
 Order By c_name asc, revenue asc, c_acctbal asc, c_phone asc, n_name asc, c_address asc, c_comment asc 
 Limit 20;

revenue desc/asc. Spurious order by attributes is still fine, but reverse ordering is a bug

**Comment by rolex4301** [comment]
https://github.com/ahanapradhan/UnionExtraction/commit/ae5cc56b8bcf581899b004ddf1bb348e48ce775f
