### ISSUE TITLE
Union query extraction does not get reflected in the UI

### ISSUE THREAD

**Issue by ahanapradhan** [ahanapradhan/UnionExtraction#75]

**Comment by ahanapradhan** [comment]
https://github.com/ahanapradhan/UnionExtraction/blob/master/mysite/unmasque/test/PipelineFactoryTest.py
Existing testcase for the backend.
Testcase name: test_union_pipeline_state

**Comment by ahanapradhan** [comment]
https://github.com/ahanapradhan/UnionExtraction/pull/79 fixes shows first subquery extraction in the UI. After that it goes to state DONE and does not show the remaining subquery extractions. Why?

**Comment by abhiraj2** [comment]
yeah, the final extracted result though has both queries, but the message passing is working in such a manner that in the progress page only first one shows up. I wasn’t sure how the layout should be to display the other query as well since we’ll need a separate set of SELECT, FROM, etc tabs
