### ISSUE TITLE
Precision error for float data type filter.

### ISSUE THREAD

**Issue by rolex4301** [ahanapradhan/UnionExtraction#99]
Q4.
hq = "SELECT p_name FROM part WHERE p_retailprice >= 0.02;"

Output
Select p_name
 From part 
 Where part.p_retailprice >= 0.03;

Note :- Here the input value is .02 but the output value comes around 0.03.

**Comment by ahanapradhan** [comment]
similar issue: https://github.com/ahanapradhan/UnionExtraction/issues/61
